#! /bin/sh
#
# Example panel for lemonbar

. panel_colors

NORMIFS=$IFS
FIELDIFS=':'

source $(dirname $0)/theme_config

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		E*)
			# symbol output
			Symbolv="%{F$WHITE}%{B$COLOR_SYS_BG}${line#?} %{B-}%{F-}"
			;;
		X*)
			# symbol output
			Symbolb="%{F$WHITE}%{B$COLOR_SYS_BG}${line#?} %{B-}%{F-}"
			;;
		Q*)
			# symbol output
			Symbolp="%{F$WHITE}%{B$COLOR_SYS_BG}${line#?} %{B-}%{F-}"
			;;
		S*)
			# clock output
			clock="%{F$LIGHTGREY}%{B$COLOR_SYS_BG}${line#?} %{B-}%{F-}"
			;;
		T*)
			# xtitle output
			title="%{F$MAGENTA}%{B$COLOR_TITLE_BG}${line#?} %{B-}%{F-}"
			;;
		N*)
			# wireless output
			wireless="%{F$LIGHTGREY}${line#?} %{B-}%{F-}"
			;;
		B*)
			# battery output
			battery="%{F$LIGHTGREY}%{B$COLOR_TITLE_BG}${line#?} %{B-}%{F-}"
			;;
		V*)
			# volume output
			volume="%{F$LIGHTGREY}%{B$COLOR_TITLE_BG}${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm's state
			wm=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					#[mM]*)
					#	[ $num_mon -lt 2 ] && shift && continue
					#	case $item in
					#		m*)
					#			# monitor
					#			FG=$COLOR_MONITOR_FG
					#			BG=$COLOR_MONITOR_BG
					#			;;
					#		M*)
					#			# focused monitor
					#			FG=$COLOR_FOCUSED_MONITOR_FG
					#			BG=$COLOR_FOCUSED_MONITOR_BG
					#			;;
					#	esac
					#	wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
					#	;;
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
                                desk="%{F$F_FG B$F_BG} ${name} %{F- B-}"
                                ;;
								# free desktop
								#FG=$COLOR_FREE_FG
								#BG=$COLOR_FREE_BG
								#;;
							F*)
								# focused free desktop
                                desk="%{F- B- U$UN_2 +u} ${name} %{F- B- -u}"
                                ;;
								# focused free desktop
								#FG=$COLOR_FOCUSED_FREE_FG
								#BG=$COLOR_FOCUSED_FREE_BG
								#;;
							o*)
								# occupied desktop
                                desk="%{F$O_FG B$O_BG} ${name} %{F- B-}"
                                ;;
								# occupied desktop
								#FG=$BLUE
								#BG=$COLOR_OCCUPIED_BG
								#;;
							O*)
								# focused occupied desktop
                                desk="%{F- B- U$UN_1 +u} ${name} %{F- B- -u}"
                                ;;
								# focused occupied desktop
								#FG=$BLUE
								#BG=$COLOR_FOCUSED_OCCUPIED_BG
								#;;
							u*)
								# urgent desktop
                                desk="%{F$U_FG B$U_BG} ${name} %{F- B-}"
                                ;;
								# urgent desktop
								#FG=$COLOR_URGENT_FG
								#BG=$COLOR_URGENT_BG
								#;;
							U*)
								# focused urgent desktop
                                desk="%{F$F_U_FG B$F_U_BG} ${name} %{F- B-}"
                                ;;
								# focused urgent desktop
								#FG=$COLOR_FOCUSED_URGENT_FG
								#BG=$COLOR_FOCUSED_URGENT_BG
								#;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:} ${desk} %{A}%{B-}%{F-}"
						;;
					[LTG]*)
						# layout, state and flags
						#wm="${wm}%{F$COLOR_STATE_FG}%{B$COLOR_STATE_BG} ${name} %{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	#printf "%s\n" "%{l}${wm}%{c}${title}%{r}${sys}"
	printf "%s\n" "%{l} ⮗ $title %{c} $wm %{r} ${wireless}${Symbolv}$volume${Symbolp}$battery${Symbolb} ${clock}"
done
