#! /bin/sh

sxhkd &
panel &

bspc config border_width         4s
bspc config window_gap          8
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config history_aware_focus     true
bspc config auto_cancel             true
bspc config apply_shadow_property true

# Settings
# bspc config auto_alternate          true
# bspc config auto_cancel             true
# bspc config adaptative_raise        true
# bspc config pointer_follows_monitor true


bspc monitor -d bspc monitor -d $(echo -e '\uf109') $(echo -e '\uf121') $(echo -e '\uf120') $(echo -e '\uf07c') $(echo -e '\uf0ac') $(echo -e '\uf0c3') $(echo -e '\uf141') $(echo -e '\uf001')

bspc desktop ^1 -l monocle

# Rules
bspc rule -a Firefox desktop=^2
bspc rule -a Gimp-2.8 desktop=^4 floating=on
bspc rule -a Gimp desktop=^4 floating=on
bspc rule -a deadbeef floating=on
bspc rule -a transmission-gtk desktop=^5
bspc rule -a lxappearance floating=on center=true
bspc rule -a nitrogen floating=on center=true
bspc rule -a file-roller floating=on center=true
